version: "3.3"

services:
  node:
    image: node:19.0.0
    volumes:
      - "/home:/home"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
      - "/etc/shadow:/etc/shadow:ro"
      - "./:/app/mvc"
    working_dir: "/app/mvc"
    ports:
      - "3000:3000"
    user: "1000:1000"
